publicHoistPattern:
    - "*eslint*"
linkWorkspacePackages: deep
preferWorkspacePackages: true
packages:
    - "packages/*"
    - "packages/examples/*"
    - "packages/config/*"
    - "packages/@typectx/*"
