publicHoistPattern:
    - "*eslint*"
    - "!@typectx/config.eslint"
linkWorkspacePackages: deep
preferWorkspacePackages: true
packages:
    - "packages/*"
    - "packages/@typectx/*"
    - "packages/@typectx/config/*"
    - "packages/@typectx/react/*"
    - "packages/@typectx/react/examples/*"
